### ISSUE TITLE
Large amount of errors causes continous restart of ioBroker.loxone

### ISSUE THREAD

**Issue by JochenKoehler** [UncleSamSwiss/ioBroker.loxone#16]
Hi,

on my system the IoBroker.loxone plugin isn't working stable unfortunately.
I'm using version 0.4.0 on a Diskstation.
Loxone config version is 9.0.9.26.

Here'ts the dump of the Logfile of IObroker:

```
host.Diskstation | 2018-04-13 19:04:01.078 | info | Restart adapter system.adapter.loxone.0 because enabled
-- | -- | -- | --
host.Diskstation | 2018-04-13 19:04:01.078 | error | instance system.adapter.loxone.0 terminated with code 0 (OK)
Caught | 2018-04-13 19:04:01.078 | error | by controller[2]: [TypeError: Cannot read property 'send' of undefined]
Caught | 2018-04-13 19:04:01.077 | error | by controller[2]: [TypeError: Cannot read property 'send' of undefined]
Caught | 2018-04-13 19:04:01.077 | error | by controller[1]: [TypeError: Cannot read property 'send' of undefined]
Caught | 2018-04-13 19:04:01.077 | error | by controller[0]: [TypeError: Cannot read property 'send' of undefined]
loxone.0 | 2018-04-13 19:04:01.043 | error | at nextTickCallbackWith1Arg (node.js:500:9)
loxone.0 | 2018-04-13 19:04:01.043 | error | at listOnTimeoutNT (timers.js:118:19)
loxone.0 | 2018-04-13 19:04:01.043 | error | at Timer.listOnTimeout (timers.js:92:15)
loxone.0 | 2018-04-13 19:04:01.043 | error | at null._onTimeout (/volume1/homes/admin/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3103:38)
loxone.0 | 2018-04-13 19:04:01.043 | error | at Adapter.emit (events.js:172:7)
loxone.0 | 2018-04-13 19:04:01.043 | error | at emitTwo (events.js:87:13)
loxone.0 | 2018-04-13 19:04:01.043 | error | at Adapter. (/volume1/homes/admin/opt/iobroker/node_modules/iobroker.loxone/loxone.js:45:29)
loxone.0 | 2018-04-13 19:04:01.043 | error | at Object.loxone.0.106bcd9f-030d-3d8f-ffff912d5ec91829.value (/volume1/homes/admin/opt/iobroker/node_modules/iobroker.loxone/loxone.js:1420:16)
loxone.0 | 2018-04-13 19:04:01.043 | error | at API.send_cmd (/volume1/homes/admin/opt/iobroker/node_modules/iobroker.loxone/node_modules/node-lox-ws-api/lib/API.js:202:10)
loxone.0 | 2018-04-13 19:04:01.043 | error | at API.send_control_command (/volume1/homes/admin/opt/iobroker/node_modules/iobroker.loxone/node_modules/node-lox-ws-api/lib/API.js:189:20)
loxone.0 | 2018-04-13 19:04:01.043 | error | TypeError: Cannot read property 'send' of undefined
loxone.0 | 2018-04-13 19:04:01.042 | error | uncaught exception: Cannot read property 'send' of undefined
loxone.0 | 2018-04-13 19:04:01.036 | error | at Timer.listOnTimeout (timers.js:92:15)
loxone.0 | 2018-04-13 19:04:01.036 | error | at null._onTimeout (/volume1/homes/admin/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3103:38)
loxone.0 | 2018-04-13 19:04:01.036 | error | at Adapter.emit (events.js:172:7)
loxone.0 | 2018-04-13 19:04:01.036 | error | at emitTwo (events.js:87:13)
loxone.0 | 2018-04-13 19:04:01.036 | error | at Adapter. (/volume1/homes/admin/opt/iobroker/node_modules/iobroker.loxone/loxone.js:45:29)
loxone.0 | 2018-04-13 19:04:01.036 | error | at Object.loxone.0.106bc915-017f-f400-ffff912d5ec91829.value (/volume1/homes/admin/opt/iobroker/node_modules/iobroker.loxone/loxone.js:1420:16)
loxone.0 | 2018-04-13 19:04:01.036 | error | at API.send_cmd (/volume1/homes/admin/opt/iobroker/node_modules/iobroker.loxone/node_modules/node-lox-ws-api/lib/API.js:202:10)
loxone.0 | 2018-04-13 19:04:01.036 | error | at API.send_control_command (/volume1/homes/admin/opt/iobroker/node_modules/iobroker.loxone/node_modules/node-lox-ws-api/lib/API.js:189:20)
loxone.0 | 2018-04-13 19:04:01.036 | error | TypeError: Cannot read property 'send' of undefined
loxone.0 | 2018-04-13 19:04:01.021 | error | uncaught exception: Cannot read property 'send' of undefined
javascript.0 | 2018-04-13 19:04:01.009 | info | script.js.common.writeStatesFromLandroid: Online true
javascript.0 | 2018-04-13 19:04:01.008 | info | script.js.common.writeStatesFromLandroid: Total Time 235.6
javascript.0 | 2018-04-13 19:04:01.007 | info | script.js.common.writeStatesFromLandroid: Error 0
javascript.0 | 2018-04-13 19:04:01.007 | info | script.js.common.writeStatesFromLandroid: Status Landroid false Status Loxone false
javascript.0 | 2018-04-13 19:04:01.007 | info | script.js.common.writeStatesFromLandroid: Status: 1
javascript.0 | 2018-04-13 19:04:01.006 | info | script.js.common.writeStatesFromLandroid: Temp 27.3
javascript.0 | 2018-04-13 19:04:01.006 | info | script.js.common.writeStatesFromLandroid: BatState 74
javascript.0 | 2018-04-13 19:04:00.747 | info | script.js.common.pingDevicesFromFritzbox: tr-064.0.devices.Handy-Christin-Moto-G5=1
javascript.0 | 2018-04-13 19:04:00.747 | info | script.js.common.pingDevicesFromFritzbox: Status Device tr-064.0.devices.Handy-Christin-Moto-G5 = true
javascript.0 | 2018-04-13 19:04:00.746 | info | script.js.common.pingDevicesFromFritzbox: tr-064.0.devices.Handy-Jochen-Moto-G4=1
javascript.0 | 2018-04-13 19:04:00.745 | info | script.js.common.pingDevicesFromFritzbox: Status Device tr-064.0.devices.Handy-Jochen-Moto-G4 = true
javascript.0 | 2018-04-13 19:04:00.618 | info | script.js.common.analyzeIncomingCalls: number of messages: 0
javascript.0 | 2018-04-13 19:04:00.617 | info | script.js.common.analyzeIncomingCalls: new message from: 0
loxone.0 | 2018-04-13 19:04:00.366 | info | connection closed
javascript.0 | 2018-04-13 19:04:00.138 | info | script.js.common.writeStatesFromLandroid: Online true
javascript.0 | 2018-04-13 19:04:00.138 | info | script.js.common.writeStatesFromLandroid: Total Time 235.6
javascript.0 | 2018-04-13 19:04:00.137 | info | script.js.common.writeStatesFromLandroid: Error 0
javascript.0 | 2018-04-13 19:04:00.137 | info | script.js.common.writeStatesFromLandroid: Status Landroid false Status Loxone false
javascript.0 | 2018-04-13 19:04:00.137 | info | script.js.common.writeStatesFromLandroid: Status: 1
javascript.0 | 2018-04-13 19:04:00.137 | info | script.js.common.writeStatesFromLandroid: Temp 27.3
javascript.0 | 2018-04-13 19:04:00.136 | info | script.js.common.writeStatesFromLandroid: BatState 74
javascript.0 | 2018-04-13 19:04:00.026 | info | script.js.common.writeStartStop: stateLandroid false
javascript.0 | 2018-04-13 19:04:00.026 | info | script.js.common.writeStartStop: stateLoxone false
admin.0 | 2018-04-13 19:03:43.036 | info | Subscribe on all states again
loxone.0 | 2018-04-13 19:03:39.480 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-04-13 19:03:39.464 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-04-13 19:03:39.453 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-04-13 19:03:39.452 | error | Unsupported control type Radio: ReferenceError: loadRadioControl is not defined
loxone.0 | 2018-04-13 19:03:39.451 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-04-13 19:03:39.449 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-04-13 19:03:39.449 | error | Unsupported control type Radio: ReferenceError: loadRadioControl is not defined
loxone.0 | 2018-04-13 19:03:39.448 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-04-13 19:03:39.447 | error | Unsupported control type Radio: ReferenceError: loadRadioControl is not defined
loxone.0 | 2018-04-13 19:03:39.446 | error | Unsupported control type Radio: ReferenceError: loadRadioControl is not defined
loxone.0 | 2018-04-13 19:03:39.442 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-04-13 19:03:39.437 | error | Unsupported control type UpDownDigital: ReferenceError: loadUpDownDigitalControl is not defined
loxone.0 | 2018-04-13 19:03:39.433 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-04-13 19:03:39.431 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-04-13 19:03:39.429 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-04-13 19:03:39.427 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-04-13 19:03:39.404 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-04-13 19:03:39.387 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-04-13 19:03:39.383 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-04-13 19:03:39.383 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-04-13 19:03:39.382 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-04-13 19:03:39.363 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-04-13 19:03:39.362 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-04-13 19:03:39.300 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-04-13 19:03:39.286 | error | Unsupported control type Radio: ReferenceError: loadRadioControl is not defined
loxone.0 | 2018-04-13 19:03:39.285 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-04-13 19:03:39.283 | error | Unsupported control type IRoomController: ReferenceError: loadIRoomControllerControl is not defined
loxone.0 | 2018-04-13 19:03:39.250 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-04-13 19:03:39.248 | error | Unsupported control type TextState: ReferenceError: loadTextStateControl is not defined
loxone.0 | 2018-04-13 19:03:39.227 | error | Unsupported control type Daytimer: ReferenceError: loadDaytimerControl is not defined
loxone.0 | 2018-04-13 19:03:39.187 | info | got structure file; last modified on 2018-03-17 12:17:42
loxone.0 | 2018-04-13 19:03:38.908 | info | Miniserver connected
loxone.0 | 2018-04-13 19:03:36.885 | info | connection closed
loxone.0 | 2018-04-13 19:03:36.542 | info | Miniserver connected
loxone.0 | 2018-04-13 19:03:34.511 | info | connection closed
loxone.0 | 2018-04-13 19:03:33.542 | info | Miniserver connected
loxone.0 | 2018-04-13 19:03:32.349 | info | starting. Version 0.4.0 in /volume1/homes/admin/opt/iobroker/node_modules/iobroker.loxone, node: v4.8.7
host.Diskstation | 2018-04-13 19:03:31.102 | info | instance system.adapter.loxone.0 started with pid 8426
```

Any hints what I could do to fix that?
Thanks and best regards
Jochen

**Comment by UncleSamSwiss** [comment]
Hi Jochen
Sorry for getting back to you so late. Did you fix this? I would suggest to use the latest version of the js-controller and perhaps update NodeJS to the latest version supported by ioBroker (I think it is 10). Unfortunately this doesn't look like something I can do anything about as the error is happening in the js-controller code: `iobroker.js-controller/lib/adapter.js:3103`.
Let me please know the state of this issue.
/UncleSam

**Comment by UncleSamSwiss** [comment]
I'm assuming this has been solved one way or the other. Please let me know if this is not the case and I should reopen this issue.

**Comment by JochenKoehler** [comment]
Hi,

thanks for your mail. I haven't had the time so far to test the new version ...

Versendet mit Email+, abgesichert durch MobileIron

-------- Originalnachricht--------
Von: Samuel Weibel <notifications@github.com<mailto:notifications@github.com>>
Datum: Sa., 27. Apr. 2019, 15:13
An: "UncleSamSwiss/ioBroker.loxone" <ioBroker.loxone@noreply.github.com<mailto:ioBroker.loxone@noreply.github.com>>
CC: Koehler Jochen FRD DIRV2 <jochen.koehler@zf.com<mailto:jochen.koehler@zf.com>>,Assign <assign@noreply.github.com<mailto:assign@noreply.github.com>>
Betreff: Re: [UncleSamSwiss/ioBroker.loxone] Large amount of errors causes continous restart of ioBroker.loxone (#16)

I'm assuming this has been solved one way or the other. Please let me know if this is not the case and I should reopen this issue.

**Comment by GermanBluefox** [comment]
@JochenKoehler please test and if still present then reopen the issue.
