### ISSUE TITLE
Instance changes to yellow several times a day

### ISSUE THREAD

**Issue by dricetea** [UncleSamSwiss/ioBroker.loxone#481]
i have installed the Loxone adapter and noticed that the instance changes to yellow several times a day - sometimes it recovers or remains faulty for a longer time. (Status of "Connected to device or service" turns red)

I have found the following entries in the ioBroker log with an indication of an authentication error:

host.ioBroker	2023-10-06 12:35:59.298	info	Restart adapter system.adapter.loxone.0 because enabled
host.ioBroker	2023-10-06 12:35:59.298	error	instance system.adapter.loxone.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[3]: at processTicksAndRejections (node:internal/process/task_queues:77:11)
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[3]: at flush (/opt/iobroker/node_modules/q/q.js:125:13)
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[3]: at runSingle (/opt/iobroker/node_modules/q/q.js:137:13)
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[3]: at /opt/iobroker/node_modules/q/q.js:624:44
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[3]: at Promise.promise.promiseDispatch (/opt/iobroker/node_modules/q/q.js:808:41)
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[3]: at Promise.when (/opt/iobroker/node_modules/q/q.js:1142:31)
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[3]: at /opt/iobroker/node_modules/q/q.js:890:30
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[3]: at _rejected (/opt/iobroker/node_modules/q/q.js:864:24)
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[3]: at _handleBadAuthResponse (/opt/iobroker/node_modules/lxcommunicator/modules/WebSocket.js:336:14)
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[3]: TypeError: Cannot read properties of undefined (reading '_setAuthenticating')
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[3]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[2]: Could not acquire a token! {"user":"admin","code":401,"value":{"lastEdit":"2009-01-01 01:00:00","unix":1230768000}}
host.ioBroker	2023-10-06 12:35:59.298	error	Caught by controller[1]: WebSocket: 401 returned during password based authentication

Debug log:
2023-10-08 11:59:21.951  - debug: loxone.0 (952839) No ackTimer for loxone.0.0d57342d-01f7-ea96-ffff690982b632a9.activeMoods
2023-10-08 12:29:15.069  - info: loxone.0 (952839) Socket closed 2004
2023-10-08 12:29:20.070  - info: loxone.0 (952839) Trying to connect
2023-10-08 12:29:23.112  - error: loxone.0 (952839) Couldn't open socket
2023-10-08 12:29:23.112  - debug: loxone.0 (952839) Connection failed - will retry after delay
2023-10-08 12:29:28.113  - info: loxone.0 (952839) Trying to connect
2023-10-08 13:33:08.387  - info: host.ioBroker stopInstance system.adapter.loxone.0 (force=false, process=true)
2023-10-08 13:33:08.388  - info: loxone.0 (952839) Got terminate signal TERMINATE_YOURSELF
2023-10-08 13:33:08.389  - info: loxone.0 (952839) terminating
2023-10-08 13:33:08.389  - debug: loxone.0 (952839) Plugin sentry destroyed
2023-10-08 13:33:08.389  - info: loxone.0 (952839) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-10-08 13:33:08.429  - info: host.ioBroker stopInstance system.adapter.loxone.0 send kill signal
2023-10-08 13:33:08.890  - info: loxone.0 (952839) terminating
2023-10-08 13:33:08.915  - info: host.ioBroker instance system.adapter.loxone.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-10-08 13:33:11.481  - info: host.ioBroker instance system.adapter.loxone.0 started with pid 998478
2023-10-08 13:33:11.879  - debug: loxone.0 (998478) Redis Objects: Use Redis connection: 127.0.0.1:9001
2023-10-08 13:33:11.898  - debug: loxone.0 (998478) Objects client ready ... initialize now
2023-10-08 13:33:11.899  - debug: loxone.0 (998478) Objects create System PubSub Client
2023-10-08 13:33:11.900  - debug: loxone.0 (998478) Objects create User PubSub Client
2023-10-08 13:33:11.926  - debug: loxone.0 (998478) Objects client initialize lua scripts
2023-10-08 13:33:11.928  - debug: loxone.0 (998478) Objects connected to redis: 127.0.0.1:9001
2023-10-08 13:33:11.945  - debug: loxone.0 (998478) Redis States: Use Redis connection: 127.0.0.1:9000
2023-10-08 13:33:11.953  - debug: loxone.0 (998478) States create System PubSub Client
2023-10-08 13:33:11.954  - debug: loxone.0 (998478) States create User PubSub Client
2023-10-08 13:33:12.010  - debug: loxone.0 (998478) States connected to redis: 127.0.0.1:9000
2023-10-08 13:33:12.063  - debug: loxone.0 (998478) Plugin sentry Initialize Plugin (enabled=true)
2023-10-08 13:33:12.187  - info: loxone.0 (998478) starting. Version 3.0.1 in /opt/iobroker/node_modules/iobroker.loxone, node: v18.18.0, js-controller: 5.0.12
2023-10-08 13:33:12.355  - info: loxone.0 (998478) Trying to connect
2023-10-08 13:33:12.578  - debug: loxone.0 (998478) token received
2023-10-08 13:33:12.643  - info: loxone.0 (998478) got structure file; last modified on 2023-09-28 16:58:13
2023-10-08 13:33:13.925  - debug: loxone.0 (998478) WeatherServer is disabled in the adapter configuration
2023-10-08 13:33:13.926  - debug: loxone.0 (998478) structure file successfully loaded

I'm using:
Loxone Adapter v3.0.1

Plattform: Proxmox / Ubuntu 22.04.3 LTS (GNU/Linux 6.2.16-14-pve x86_64)
RAM: 4 GB
Node.js: v18.18.0
NPM: 9.8.1

Miniserver: 14.2.6.16

Any idea how to keep the adapter stable?

Best regards,
Dr Icetea

**Comment by dricetea** [comment]
In order to rule out various factors or to better isolate the problem, I created a new debian container and installed iobroker and loxone adapter - after a short time this also became unstable...

Yesterday I updated the Miniserver to 14.4.9.25 - since then I haven't seen any problems with the Loxone Adapter and I hope it stays that way.

**Comment by raintonr** [comment]
Closing as no further updates.
